spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/calender
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true    // JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    show-sql: true
  properties:
    hibernate:
  # show_sql: true
    format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

server:
#  error:
#    include-message: always
#    include-binding-errors: always
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie